name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: pnpm/action-setup@v2
      with:
        version: 10.22.0
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests Employer
      run: pnpm exec playwright test PIM.spec --reporter=junit --output=playwright-report/employer
      env:
        CI: true
      continue-on-error: true
    - name: Run Playwright tests Admin
      run: pnpm exec playwright test Admin.spec --reporter=junit --output=playwright-report/admin
      env:
        CI: true
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
